USE EjaysMagic

-- 1. View all products and their prices
SELECT ProductName, Price
FROM Products

-- 2. View products with a price of exactly £40
SELECT ProductName, Price
FROM Products
WHERE Price = 40

-- 3. Arrange products from lowest to highest price
SELECT ProductName, Price
FROM Products
ORDER BY Price ASC

-- 4. View products priced at £25 or above arranged from highest to lowest
SELECT ProductName, Price
FROM Products
WHERE Price >= 25 
ORDER BY Price ASC

--5. Calculate the total of all listed product prices
SELECT SUM(Price) AS TotalProductValue
FROM Products

--6. Count the total number of products
SELECT COUNT(*) AS TotalProducts
FROM Products

--7. Calculate the average price
SELECT AVG(Price) AS AveragePrice
FROM Products

--8. Count how many order-detail records contain each product
SELECT ProductID,
COUNT(*) AS TimesOrdered
FROM OrdersDetails
GROUP BY ProductID

--9. Calculate the total quantity sold for each productID
SELECT ProductID,
SUM(Quantity) AS TotalQuantitySold
FROM OrdersDetails
GROUP BY ProductID

--10. Join ordersdetails to products to show product names alongside the quantity in each order-detail record
SELECT Products.ProductName, OrdersDetails.Quantity
FROM OrdersDetails
JOIN Products
ON OrdersDetails.ProductID = Products.ProductID

--11. Calculate total quantity sold for each product and arrange from highest to lowest
SELECT Products.ProductName,
SUM(OrdersDetails.Quantity) AS TotalQuantitySold
FROM OrdersDetails
JOIN Products
ON OrdersDetails.ProductID = Products.ProductID
GROUP BY Products.ProductName
ORDER BY TotalQuantitySold DESC

--12. Calculate revenue for each individual order-detail row
SELECT ProductID, Quantity, UnitPrice, Quantity*UnitPrice ASRevenue
FROM OrdersDetails

--13. Calculate total revenue generated by each product
SELECT Products.ProductName,
SUM(OrdersDetails.Quantity * OrdersDetails.UnitPrice) AS TotalRevenue
FROM OrdersDetails
JOIN Products
ON OrdersDetails.ProductID = Products.ProductID
GROUP BY Products. ProductName
ORDER BY TotalRevenue DESC

--14. Show products that generated more than £50 in total revenue
SELECT Products.ProductName,
SUM(OrdersDetails.Quantity * OrdersDetails. UnitPrice) AS TotalRevenue
FROM OrdersDetails
JOIN Products
ON OrdersDetails.ProductID = Products.ProductID
GROUP BY Products.ProductName
HAVING SUM(OrdersDetails.Quantity * OrdersDetails.UnitPrice)> 50
ORDER BY TotalRevenue DESC

--15. Calculate total business revenue
SELECT SUM(Quantity * UnitPrice) As TotalRevenue
FROM OrdersDetails

--16. Show the 5 most expensive products
SELECT TOP 5 ProductName, Price
FROM Products
ORDER BY Price DESC

--17. Show unique productIDs that have been ordered
SELECT DISTINCT
ProductID
FROM OrdersDetails

--18. Find order details were product size is not recorded
SELECT *
FROM OrdersDetails
WHERE ProductSizeID is NULL

--19. Find order details where product size is recorded
SELECT *
FROM OrdersDetails
WHERE ProductSizeID is not NULL

--20. Categorise products according to price
SELECT
ProductName, Price,
CASE 
WHEN Price >= 40 THEN 'High Price'
ELSE 'Standard Price'
END AS PriceCategory
FROM Products

